//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentDefinition) DeepCopyInto(out *ComponentDefinition) {
	*out = *in
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(GroupVersionKind)
		**out = **in
	}
	if in.OwnerRef != nil {
		in, out := &in.OwnerRef, &out.OwnerRef
		*out = new(string)
		**out = **in
	}
	if in.SpecDefinition != nil {
		in, out := &in.SpecDefinition, &out.SpecDefinition
		*out = new(SpecDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleDefinition != nil {
		in, out := &in.ScaleDefinition, &out.ScaleDefinition
		*out = new(ScaleDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.StatusDefinition != nil {
		in, out := &in.StatusDefinition, &out.StatusDefinition
		*out = new(StatusDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.SuspendDefinition != nil {
		in, out := &in.SuspendDefinition, &out.SuspendDefinition
		*out = new(SuspendDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceIds != nil {
		in, out := &in.InstanceIds, &out.InstanceIds
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(PodSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentDefinition.
func (in *ComponentDefinition) DeepCopy() *ComponentDefinition {
	if in == nil {
		return nil
	}
	out := new(ComponentDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentInstanceSelector) DeepCopyInto(out *ComponentInstanceSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentInstanceSelector.
func (in *ComponentInstanceSelector) DeepCopy() *ComponentInstanceSelector {
	if in == nil {
		return nil
	}
	out := new(ComponentInstanceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentTypeSelector) DeepCopyInto(out *ComponentTypeSelector) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentTypeSelector.
func (in *ComponentTypeSelector) DeepCopy() *ComponentTypeSelector {
	if in == nil {
		return nil
	}
	out := new(ComponentTypeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsDefinition) DeepCopyInto(out *ConditionsDefinition) {
	*out = *in
	if in.MessageFieldName != nil {
		in, out := &in.MessageFieldName, &out.MessageFieldName
		*out = new(string)
		**out = **in
	}
	if in.ReasonFieldName != nil {
		in, out := &in.ReasonFieldName, &out.ReasonFieldName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsDefinition.
func (in *ConditionsDefinition) DeepCopy() *ConditionsDefinition {
	if in == nil {
		return nil
	}
	out := new(ConditionsDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedCondition) DeepCopyInto(out *ExpectedCondition) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedCondition.
func (in *ExpectedCondition) DeepCopy() *ExpectedCondition {
	if in == nil {
		return nil
	}
	out := new(ExpectedCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpressionMatcher) DeepCopyInto(out *ExpressionMatcher) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpressionMatcher.
func (in *ExpressionMatcher) DeepCopy() *ExpressionMatcher {
	if in == nil {
		return nil
	}
	out := new(ExpressionMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FragmentedPodSpecDefinition) DeepCopyInto(out *FragmentedPodSpecDefinition) {
	*out = *in
	if in.SchedulerName != nil {
		in, out := &in.SchedulerName, &out.SchedulerName
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.ResourceClaims != nil {
		in, out := &in.ResourceClaims, &out.ResourceClaims
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.PodAffinity != nil {
		in, out := &in.PodAffinity, &out.PodAffinity
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.PriorityClassName != nil {
		in, out := &in.PriorityClassName, &out.PriorityClassName
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ValueAccessor)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FragmentedPodSpecDefinition.
func (in *FragmentedPodSpecDefinition) DeepCopy() *FragmentedPodSpecDefinition {
	if in == nil {
		return nil
	}
	out := new(FragmentedPodSpecDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GangSchedulingInstruction) DeepCopyInto(out *GangSchedulingInstruction) {
	*out = *in
	if in.PodGroups != nil {
		in, out := &in.PodGroups, &out.PodGroups
		*out = make([]PodGroupDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodGroup != nil {
		in, out := &in.PodGroup, &out.PodGroup
		*out = new(PodGroupComponentsMapping)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GangSchedulingInstruction.
func (in *GangSchedulingInstruction) DeepCopy() *GangSchedulingInstruction {
	if in == nil {
		return nil
	}
	out := new(GangSchedulingInstruction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupVersionKind) DeepCopyInto(out *GroupVersionKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupVersionKind.
func (in *GroupVersionKind) DeepCopy() *GroupVersionKind {
	if in == nil {
		return nil
	}
	out := new(GroupVersionKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Karta) DeepCopyInto(out *Karta) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Karta.
func (in *Karta) DeepCopy() *Karta {
	if in == nil {
		return nil
	}
	out := new(Karta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Karta) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KartaList) DeepCopyInto(out *KartaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Karta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KartaList.
func (in *KartaList) DeepCopy() *KartaList {
	if in == nil {
		return nil
	}
	out := new(KartaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KartaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KartaSpec) DeepCopyInto(out *KartaSpec) {
	*out = *in
	in.StructureDefinition.DeepCopyInto(&out.StructureDefinition)
	in.Instructions.DeepCopyInto(&out.Instructions)
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]Variable, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KartaSpec.
func (in *KartaSpec) DeepCopy() *KartaSpec {
	if in == nil {
		return nil
	}
	out := new(KartaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KartaStatus) DeepCopyInto(out *KartaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KartaStatus.
func (in *KartaStatus) DeepCopy() *KartaStatus {
	if in == nil {
		return nil
	}
	out := new(KartaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KartaValidator) DeepCopyInto(out *KartaValidator) {
	*out = *in
	if in.karta != nil {
		in, out := &in.karta, &out.karta
		*out = new(Karta)
		(*in).DeepCopyInto(*out)
	}
	in.rootComponent.DeepCopyInto(&out.rootComponent)
	if in.allComponents != nil {
		in, out := &in.allComponents, &out.allComponents
		*out = make(map[string]ComponentDefinition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KartaValidator.
func (in *KartaValidator) DeepCopy() *KartaValidator {
	if in == nil {
		return nil
	}
	out := new(KartaValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelSelectorRequirement) DeepCopyInto(out *LabelSelectorRequirement) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]LabelValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelectorRequirement.
func (in *LabelSelectorRequirement) DeepCopy() *LabelSelectorRequirement {
	if in == nil {
		return nil
	}
	out := new(LabelSelectorRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelValue) DeepCopyInto(out *LabelValue) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelValue.
func (in *LabelValue) DeepCopy() *LabelValue {
	if in == nil {
		return nil
	}
	out := new(LabelValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListReference) DeepCopyInto(out *ListReference) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]LabelValue, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListReference.
func (in *ListReference) DeepCopy() *ListReference {
	if in == nil {
		return nil
	}
	out := new(ListReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LookupReference) DeepCopyInto(out *LookupReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LookupReference.
func (in *LookupReference) DeepCopy() *LookupReference {
	if in == nil {
		return nil
	}
	out := new(LookupReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationInstructions) DeepCopyInto(out *OptimizationInstructions) {
	*out = *in
	if in.GangScheduling != nil {
		in, out := &in.GangScheduling, &out.GangScheduling
		*out = new(GangSchedulingInstruction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationInstructions.
func (in *OptimizationInstructions) DeepCopy() *OptimizationInstructions {
	if in == nil {
		return nil
	}
	out := new(OptimizationInstructions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseDefinition) DeepCopyInto(out *PhaseDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseDefinition.
func (in *PhaseDefinition) DeepCopy() *PhaseDefinition {
	if in == nil {
		return nil
	}
	out := new(PhaseDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupComponentsMapping) DeepCopyInto(out *PodGroupComponentsMapping) {
	*out = *in
	if in.SubGroups != nil {
		in, out := &in.SubGroups, &out.SubGroups
		*out = make([]SubGroupComponentMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(TopologyConstraint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupComponentsMapping.
func (in *PodGroupComponentsMapping) DeepCopy() *PodGroupComponentsMapping {
	if in == nil {
		return nil
	}
	out := new(PodGroupComponentsMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupDefinition) DeepCopyInto(out *PodGroupDefinition) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]PodGroupMemberDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupDefinition.
func (in *PodGroupDefinition) DeepCopy() *PodGroupDefinition {
	if in == nil {
		return nil
	}
	out := new(PodGroupDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupMemberDefinition) DeepCopyInto(out *PodGroupMemberDefinition) {
	*out = *in
	if in.GroupByExpressions != nil {
		in, out := &in.GroupByExpressions, &out.GroupByExpressions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupMemberDefinition.
func (in *PodGroupMemberDefinition) DeepCopy() *PodGroupMemberDefinition {
	if in == nil {
		return nil
	}
	out := new(PodGroupMemberDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSelector) DeepCopyInto(out *PodSelector) {
	*out = *in
	if in.ComponentTypeSelector != nil {
		in, out := &in.ComponentTypeSelector, &out.ComponentTypeSelector
		*out = new(ComponentTypeSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ComponentInstanceSelector != nil {
		in, out := &in.ComponentInstanceSelector, &out.ComponentInstanceSelector
		*out = new(ComponentInstanceSelector)
		**out = **in
	}
	if in.ReplicaSelector != nil {
		in, out := &in.ReplicaSelector, &out.ReplicaSelector
		*out = new(ReplicaSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSelector.
func (in *PodSelector) DeepCopy() *PodSelector {
	if in == nil {
		return nil
	}
	out := new(PodSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaSelector) DeepCopyInto(out *ReplicaSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaSelector.
func (in *ReplicaSelector) DeepCopy() *ReplicaSelector {
	if in == nil {
		return nil
	}
	out := new(ReplicaSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
	out.GVK = in.GVK
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = new(LookupReference)
		**out = **in
	}
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = new(ListReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleDefinition) DeepCopyInto(out *ScaleDefinition) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(ValueAccessor)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleDefinition.
func (in *ScaleDefinition) DeepCopy() *ScaleDefinition {
	if in == nil {
		return nil
	}
	out := new(ScaleDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecDefinition) DeepCopyInto(out *SpecDefinition) {
	*out = *in
	if in.PodTemplateSpec != nil {
		in, out := &in.PodTemplateSpec, &out.PodTemplateSpec
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.PodSpec != nil {
		in, out := &in.PodSpec, &out.PodSpec
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(ValueAccessor)
		**out = **in
	}
	if in.FragmentedPodSpecDefinition != nil {
		in, out := &in.FragmentedPodSpecDefinition, &out.FragmentedPodSpecDefinition
		*out = new(FragmentedPodSpecDefinition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecDefinition.
func (in *SpecDefinition) DeepCopy() *SpecDefinition {
	if in == nil {
		return nil
	}
	out := new(SpecDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusDefinition) DeepCopyInto(out *StatusDefinition) {
	*out = *in
	if in.PhaseDefinition != nil {
		in, out := &in.PhaseDefinition, &out.PhaseDefinition
		*out = new(PhaseDefinition)
		**out = **in
	}
	if in.ConditionsDefinition != nil {
		in, out := &in.ConditionsDefinition, &out.ConditionsDefinition
		*out = new(ConditionsDefinition)
		(*in).DeepCopyInto(*out)
	}
	in.StatusMappings.DeepCopyInto(&out.StatusMappings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusDefinition.
func (in *StatusDefinition) DeepCopy() *StatusDefinition {
	if in == nil {
		return nil
	}
	out := new(StatusDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusMappings) DeepCopyInto(out *StatusMappings) {
	*out = *in
	if in.Initializing != nil {
		in, out := &in.Initializing, &out.Initializing
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Completed != nil {
		in, out := &in.Completed, &out.Completed
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Suspended != nil {
		in, out := &in.Suspended, &out.Suspended
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Suspending != nil {
		in, out := &in.Suspending, &out.Suspending
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resuming != nil {
		in, out := &in.Resuming, &out.Resuming
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusMappings.
func (in *StatusMappings) DeepCopy() *StatusMappings {
	if in == nil {
		return nil
	}
	out := new(StatusMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusMatchEntry) DeepCopyInto(out *StatusMatchEntry) {
	*out = *in
	if in.Matchers != nil {
		in, out := &in.Matchers, &out.Matchers
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusMatchEntry.
func (in *StatusMatchEntry) DeepCopy() *StatusMatchEntry {
	if in == nil {
		return nil
	}
	out := new(StatusMatchEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusMatcher) DeepCopyInto(out *StatusMatcher) {
	*out = *in
	if in.ByConditions != nil {
		in, out := &in.ByConditions, &out.ByConditions
		*out = make([]ExpectedCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ByExpression != nil {
		in, out := &in.ByExpression, &out.ByExpression
		*out = new(ExpressionMatcher)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusMatcher.
func (in *StatusMatcher) DeepCopy() *StatusMatcher {
	if in == nil {
		return nil
	}
	out := new(StatusMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructureDefinition) DeepCopyInto(out *StructureDefinition) {
	*out = *in
	in.RootComponent.DeepCopyInto(&out.RootComponent)
	if in.ChildComponents != nil {
		in, out := &in.ChildComponents, &out.ChildComponents
		*out = make([]ComponentDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdditionalChildKinds != nil {
		in, out := &in.AdditionalChildKinds, &out.AdditionalChildKinds
		*out = make([]GroupVersionKind, len(*in))
		copy(*out, *in)
	}
	if in.References != nil {
		in, out := &in.References, &out.References
		*out = make([]ResourceReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructureDefinition.
func (in *StructureDefinition) DeepCopy() *StructureDefinition {
	if in == nil {
		return nil
	}
	out := new(StructureDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubGroupComponentMapping) DeepCopyInto(out *SubGroupComponentMapping) {
	*out = *in
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(TopologyConstraint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubGroupComponentMapping.
func (in *SubGroupComponentMapping) DeepCopy() *SubGroupComponentMapping {
	if in == nil {
		return nil
	}
	out := new(SubGroupComponentMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuspendAction) DeepCopyInto(out *SuspendAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuspendAction.
func (in *SuspendAction) DeepCopy() *SuspendAction {
	if in == nil {
		return nil
	}
	out := new(SuspendAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuspendDefinition) DeepCopyInto(out *SuspendDefinition) {
	*out = *in
	if in.SuspendActions != nil {
		in, out := &in.SuspendActions, &out.SuspendActions
		*out = make([]SuspendAction, len(*in))
		copy(*out, *in)
	}
	if in.ResumeActions != nil {
		in, out := &in.ResumeActions, &out.ResumeActions
		*out = make([]SuspendAction, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuspendDefinition.
func (in *SuspendDefinition) DeepCopy() *SuspendDefinition {
	if in == nil {
		return nil
	}
	out := new(SuspendDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyConstraint) DeepCopyInto(out *TopologyConstraint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyConstraint.
func (in *TopologyConstraint) DeepCopy() *TopologyConstraint {
	if in == nil {
		return nil
	}
	out := new(TopologyConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueAccessor) DeepCopyInto(out *ValueAccessor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueAccessor.
func (in *ValueAccessor) DeepCopy() *ValueAccessor {
	if in == nil {
		return nil
	}
	out := new(ValueAccessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Variable) DeepCopyInto(out *Variable) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Variable.
func (in *Variable) DeepCopy() *Variable {
	if in == nil {
		return nil
	}
	out := new(Variable)
	in.DeepCopyInto(out)
	return out
}
