# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
# 05b plus an interval-free age check: the job must already have been Running
# two minutes ago (offset 2m), so a job born after the rule waits its window
# without the rule knowing the scrape interval.
apiVersion: policies.kyverno.io/v1beta1
kind: MutatingPolicy
metadata:
  name: metric-suspend-off
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["jobs"]
  evaluation:
    admission:
      enabled: false
    mutateExisting:
      enabled: true
  targetMatchConditions:
    - name: only-trainer-off
      expression: "object.metadata.name == 'trainer-off'"
    - name: not-already-suspended
      expression: "!object.spec.?suspend.orValue(false)"
    - name: running-2m-and-existed-2m-ago
      expression: >-
        object.metadata.name in
        http.Get('http://prometheus.monitoring.svc:9090/api/v1/query?query=min_over_time%28karta_workload_status%7Bnamespace%3D%22ai-team%22%2Cphase%3D%22Running%22%2Cworkload_kind%3D%22Job%22%7D%5B2m%5D%29%3D%3D1%20and%20karta_workload_status%7Bnamespace%3D%22ai-team%22%2Cphase%3D%22Running%22%2Cworkload_kind%3D%22Job%22%7D%20offset%202m%20%3D%3D%201')
        .data.result.map(r, r.metric.workload)
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: >-
          [JSONPatch{op: 'add', path: '/spec/suspend', value: true}]
