# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: apps-statefulset-v1
spec:
  structureDefinition:
    rootComponent:
      name: statefulset
      kind:
        group: apps
        version: v1
        kind: StatefulSet
      specDefinition:
        podTemplateSpec:
          expression: object[?"spec"][?"template"].orValue(null)
          patch: '{"spec": {"template": value}}'
          replace: true
      scaleDefinition:
        replicas:
          expression: variables.specReplicas
      statusDefinition:
        statusMappings:
          initializing:
            - byExpression:
                expression: variables.specReplicasOne > 0 && (variables.statusObservedGeneration != variables.metadataGeneration || variables.statusReadyReplicas == 0 || variables.statusReadyReplicas > variables.specReplicasOne || variables.statusUpdatedReplicas != variables.specReplicasOne || variables.statusCurrentRevision != variables.statusUpdateRevision)
                expectedResult: "true"
          running:
            - byExpression:
                expression: variables.statusObservedGeneration == variables.metadataGeneration && variables.statusReadyReplicas == variables.specReplicasOne && variables.statusUpdatedReplicas == variables.specReplicasOne && variables.statusCurrentRevision == variables.statusUpdateRevision
                expectedResult: "true"
          degraded:
            - byExpression:
                expression: variables.statusReadyReplicas > 0 && variables.statusReadyReplicas < variables.specReplicasOne && variables.statusUpdatedReplicas == variables.specReplicasOne && variables.statusCurrentRevision == variables.statusUpdateRevision && variables.statusObservedGeneration == variables.metadataGeneration
                expectedResult: "true"
  optimizationInstructions: {}
  variables:
    - name: specReplicas
      expression: ([dyn(object[?"spec"][?"replicas"].orValue(null))].filter(v, v != null && v != false) + [1])[0]
    - name: statusObservedGeneration
      expression: ([dyn(object.?status.?observedGeneration.orValue(null))].filter(v, v != null && v != false) + [0])[0]
    - name: metadataGeneration
      expression: ([dyn(object.?metadata.?generation.orValue(null))].filter(v, v != null && v != false) + [0])[0]
    - name: statusReadyReplicas
      expression: ([dyn(object.?status.?readyReplicas.orValue(null))].filter(v, v != null && v != false) + [0])[0]
    - name: specReplicasOne
      expression: ([dyn(object.?spec.?replicas.orValue(null))].filter(v, v != null && v != false) + [1])[0]
    - name: statusUpdatedReplicas
      expression: ([dyn(object.?status.?updatedReplicas.orValue(null))].filter(v, v != null && v != false) + [0])[0]
    - name: statusCurrentRevision
      expression: ([dyn(object.?status.?currentRevision.orValue(null))].filter(v, v != null && v != false) + [""])[0]
    - name: statusUpdateRevision
      expression: ([dyn(object.?status.?updateRevision.orValue(null))].filter(v, v != null && v != false) + [""])[0]
