# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: core-pod-v1
spec:
  structureDefinition:
    rootComponent:
      name: pod
      kind:
        group: ""
        version: v1
        kind: Pod
      specDefinition:
        podTemplateSpec:
          expression: object
          patch: value
          replace: true
      scaleDefinition:
        replicas:
          expression: "1"
      statusDefinition:
        phaseDefinition:
          expression: object[?"status"][?"phase"].orValue(null)
        conditionsDefinition:
          expression: object[?"status"][?"conditions"].orValue(null)
          typeFieldName: type
          statusFieldName: status
          messageFieldName: message
          reasonFieldName: reason
        statusMappings:
          initializing:
            - byPhase: Pending
          running:
            - byPhase: Running
          completed:
            - byPhase: Succeeded
          failed:
            - byPhase: Failed
  optimizationInstructions: {}
