# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: nvidia-com-dynamographdeployment-v1beta1
spec:
  structureDefinition:
    rootComponent:
      name: dynamographdeployment
      kind:
        group: nvidia.com
        version: v1beta1
        kind: DynamoGraphDeployment
      statusDefinition:
        phaseDefinition:
          expression: object[?"status"][?"state"].orValue(null)
        statusMappings:
          initializing:
            - byPhase: initializing
            - byPhase: pending
          running:
            - byPhase: successful
          failed:
            - byPhase: failed
    childComponents:
      - name: component
        ownerRef: dynamographdeployment
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerName:
              expression: ([dyn(object[?"spec"][?"components"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"podTemplate"][?"spec"][?"schedulerName"].orValue(null))
              patch: '[{"op": "add", "path": "/spec/components/" + string(index) + "/podTemplate/spec/schedulerName", "value": value}]'
            labels:
              expression: ([dyn(object[?"spec"][?"components"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"podTemplate"][?"metadata"][?"labels"].orValue(null))
              patch: '[{"op": "add", "path": "/spec/components/" + string(index) + "/podTemplate/metadata/labels", "value": value}]'
            annotations:
              expression: ([dyn(object[?"spec"][?"components"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"podTemplate"][?"metadata"][?"annotations"].orValue(null))
              patch: '[{"op": "add", "path": "/spec/components/" + string(index) + "/podTemplate/metadata/annotations", "value": value}]'
            resourceClaims:
              expression: ([dyn(object[?"spec"][?"components"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"podTemplate"][?"spec"][?"resourceClaims"].orValue(null))
              patch: '[{"op": "add", "path": "/spec/components/" + string(index) + "/podTemplate/spec/resourceClaims", "value": value}]'
            podAffinity:
              expression: ([dyn(object[?"spec"][?"components"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"podTemplate"][?"spec"][?"affinity"][?"podAffinity"].orValue(null))
              patch: '[{"op": "add", "path": "/spec/components/" + string(index) + "/podTemplate/spec/affinity/podAffinity", "value": value}]'
            nodeAffinity:
              expression: ([dyn(object[?"spec"][?"components"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"podTemplate"][?"spec"][?"affinity"][?"nodeAffinity"].orValue(null))
              patch: '[{"op": "add", "path": "/spec/components/" + string(index) + "/podTemplate/spec/affinity/nodeAffinity", "value": value}]'
            container:
              expression: ([dyn(object[?"spec"][?"components"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, (([dyn(x[?"podTemplate"][?"spec"][?"containers"].orValue(null))].filter(v, type(v) == list) + [[]])[0].filter(c, c[?"name"].orValue("") == "main") + [null])[0])
            priorityClassName:
              expression: ([dyn(object[?"spec"][?"components"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"podTemplate"][?"spec"][?"priorityClassName"].orValue(null))
              patch: '[{"op": "add", "path": "/spec/components/" + string(index) + "/podTemplate/spec/priorityClassName", "value": value}]'
            image:
              expression: ([dyn(object[?"spec"][?"components"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, ((([dyn(x[?"podTemplate"][?"spec"][?"containers"].orValue(null))].filter(v, type(v) == list) + [[]])[0].filter(c, c[?"name"].orValue("") == "main") + [{}])[0])[?"image"].orValue(null))
        scaleDefinition:
          replicas:
            expression: variables.components.map(x, ([dyn(x.?replicas.orValue(null))].filter(v, v != null && v != false) + [1.0])[0] * ([dyn(x.?multinode.?nodeCount.orValue(null))].filter(v, v != null && v != false) + [1.0])[0])
        instanceIds:
          expression: ([dyn(object[?"spec"][?"components"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"name"].orValue(null))
        podSelector:
          componentInstanceSelector:
            expression: object[?"metadata"][?"labels"][?"nvidia.com/dynamo-component"].orValue(null)
          replicaSelector:
            expression: object[?"metadata"][?"labels"][?"grove.io/podcliquescalinggroup-replica-index"].orValue(object[?"metadata"][?"labels"][?"leaderworkerset.sigs.k8s.io/group-index"].orValue(null))
    additionalChildKinds:
      - group: nvidia.com
        version: v1beta1
        kind: DynamoComponentDeployment
      - group: leaderworkerset.x-k8s.io
        version: v1
        kind: LeaderWorkerSet
      - group: scheduler.grove.io
        version: v1alpha1
        kind: PodGang
      - group: grove.io
        version: v1alpha1
        kind: PodClique
      - group: grove.io
        version: v1alpha1
        kind: PodCliqueSet
      - group: grove.io
        version: v1alpha1
        kind: PodCliqueScalingGroup
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: component
          members:
            - componentName: component
              groupByExpressions:
                - object[?"metadata"][?"labels"][?"nvidia.com/dynamo-component"].orValue(null).lowerAscii()
  variables:
    - name: components
      expression: ([dyn(object[?"spec"][?"components"].orValue(null))].filter(v, type(v) == list) + [[]])[0]
