# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: ray-io-raycluster-v1
spec:
  structureDefinition:
    rootComponent:
      name: raycluster
      kind:
        group: ray.io
        version: v1
        kind: RayCluster
      statusDefinition:
        phaseDefinition:
          expression: object[?"status"][?"state"].orValue(null)
        statusMappings:
          initializing:
            - byExpression:
                expression: object.?spec.?suspend.orValue(false) != true && variables.statusState != "ready" && variables.statusState != "failed"
                expectedResult: "true"
          running:
            - byPhase: ready
          failed:
            - byPhase: failed
          suspended:
            - byExpression:
                expression: object.?spec.?suspend.orValue(false) == true && (variables.statusState == "suspended" || variables.statusState == "")
                expectedResult: "true"
      suspendDefinition:
        suspendActions:
          - patch: '{"spec": {"suspend": true}}'
        resumeActions:
          - patch: '{"spec": {"suspend": false}}'
    childComponents:
      - name: head
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: raycluster
        specDefinition:
          podTemplateSpec:
            expression: object[?"spec"][?"headGroupSpec"][?"template"].orValue(null)
            patch: '{"spec": {"headGroupSpec": {"template": value}}}'
            replace: true
        scaleDefinition:
          replicas:
            expression: "1"
        podSelector:
          componentTypeSelector:
            expression: object[?"metadata"][?"labels"][?"ray.io/node-type"].orValue(null)
            value: head
      - name: worker
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: raycluster
        specDefinition:
          podTemplateSpec:
            expression: ([dyn(object[?"spec"][?"workerGroupSpecs"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"template"].orValue(null))
            patch: '[{"op": "add", "path": "/spec/workerGroupSpecs/" + string(index) + "/template", "value": value}]'
        scaleDefinition:
          replicas:
            expression: ([dyn(object[?"spec"][?"workerGroupSpecs"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"replicas"].orValue(null))
          minReplicas:
            expression: ([dyn(object[?"spec"][?"workerGroupSpecs"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"minReplicas"].orValue(null))
          maxReplicas:
            expression: ([dyn(object[?"spec"][?"workerGroupSpecs"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"maxReplicas"].orValue(null))
        instanceIds:
          expression: ([dyn(object[?"spec"][?"workerGroupSpecs"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"groupName"].orValue(null))
        podSelector:
          componentTypeSelector:
            expression: object[?"metadata"][?"labels"][?"ray.io/node-type"].orValue(null)
            value: worker
          componentInstanceSelector:
            expression: object[?"metadata"][?"labels"][?"ray.io/group"].orValue(null)
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: cluster
          members:
            - componentName: head
              groupByExpressions:
                - object[?"metadata"][?"labels"][?"ray.io/cluster"].orValue(null)
            - componentName: worker
              groupByExpressions:
                - object[?"metadata"][?"labels"][?"ray.io/cluster"].orValue(null)
  variables:
    - name: statusState
      expression: ([dyn(object.?status.?state.orValue(null))].filter(v, v != null && v != false) + [""])[0]
