# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: ray-io-rayservice-v1
spec:
  structureDefinition:
    rootComponent:
      name: rayservice
      kind:
        group: ray.io
        version: v1
        kind: RayService
      statusDefinition:
        conditionsDefinition:
          expression: object[?"status"][?"conditions"].orValue(null)
          typeFieldName: type
          statusFieldName: status
          messageFieldName: message
          reasonFieldName: reason
        statusMappings:
          initializing:
            - byConditions:
                - type: Ready
                  status: "False"
                  reason: Initializing
          running:
            - byConditions:
                - type: Ready
                  status: "True"
          failed:
            - byConditions:
                - type: Ready
                  status: "False"
                  reason: InitializingTimeout
            - byConditions:
                - type: Ready
                  status: "False"
                  reason: ValidationFailed
          degraded:
            - byConditions:
                - type: Ready
                  status: "False"
                  reason: ZeroServeEndpoints
    childComponents:
      - name: head
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: rayservice
        specDefinition:
          podTemplateSpec:
            expression: object[?"spec"][?"rayClusterConfig"][?"headGroupSpec"][?"template"].orValue(null)
            patch: '{"spec": {"rayClusterConfig": {"headGroupSpec": {"template": value}}}}'
            replace: true
        scaleDefinition:
          replicas:
            expression: "1"
        podSelector:
          componentTypeSelector:
            expression: object[?"metadata"][?"labels"][?"ray.io/node-type"].orValue(null)
            value: head
      - name: worker
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: rayservice
        specDefinition:
          podTemplateSpec:
            expression: ([dyn(object[?"spec"][?"rayClusterConfig"][?"workerGroupSpecs"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"template"].orValue(null))
            patch: '[{"op": "add", "path": "/spec/rayClusterConfig/workerGroupSpecs/" + string(index) + "/template", "value": value}]'
        scaleDefinition:
          replicas:
            expression: '(variables.workerReplicas.size() > 0 ? variables.workerReplicas : [dyn(1)])'
        instanceIds:
          expression: ([dyn(object[?"spec"][?"rayClusterConfig"][?"workerGroupSpecs"].orValue(null))].filter(v, type(v) == list) + [[]])[0].map(x, x[?"groupName"].orValue(null))
        podSelector:
          componentTypeSelector:
            expression: object[?"metadata"][?"labels"][?"ray.io/node-type"].orValue(null)
            value: worker
          componentInstanceSelector:
            expression: object[?"metadata"][?"labels"][?"ray.io/group"].orValue(null)
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: service
          members:
            - componentName: head
              groupByExpressions:
                - object[?"metadata"][?"labels"][?"ray.io/cluster"].orValue(null)
            - componentName: worker
              groupByExpressions:
                - object[?"metadata"][?"labels"][?"ray.io/cluster"].orValue(null)
  variables:
    - name: workerGroups
      expression: ([dyn(object[?"spec"][?"rayClusterConfig"][?"workerGroupSpecs"].orValue(null))].filter(v, type(v) == list) + [[]])[0]
    - name: workerReplicas
      expression: variables.workerGroups.map(x, dyn(x[?"replicas"].orValue(null))).filter(v, v != null && v != false)
