# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: serving-knative-dev-service-v1
spec:
  structureDefinition:
    rootComponent:
      name: knativeservice
      kind:
        group: serving.knative.dev
        version: v1
        kind: Service
      statusDefinition:
        conditionsDefinition:
          expression: object[?"status"][?"conditions"].orValue(null)
          typeFieldName: type
          statusFieldName: status
          messageFieldName: message
        statusMappings:
          initializing:
            - byConditions:
                - type: Ready
                  status: Unknown
          running:
            - byConditions:
                - type: Ready
                  status: "True"
          failed:
            - byConditions:
                - type: Ready
                  status: "False"
    childComponents:
      - name: revision
        kind:
          group: serving.knative.dev
          version: v1
          kind: Revision
        ownerRef: knativeservice
        specDefinition:
          podTemplateSpec:
            expression: object[?"spec"][?"template"].orValue(null)
            patch: '{"spec": {"template": value}}'
            replace: true
        scaleDefinition:
          minReplicas:
            expression: variables.minScale
          maxReplicas:
            expression: object[?"spec"][?"template"][?"metadata"][?"annotations"][?"autoscaling.knative.dev/max-scale"].orValue(null)
    additionalChildKinds:
      - group: apps
        version: v1
        kind: Deployment
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: revision
          members:
            - componentName: revision
              groupByExpressions:
                - object[?"metadata"][?"labels"][?"serving.knative.dev/revision"].orValue(null)
  variables:
    - name: minScale
      expression: ([dyn(object[?"spec"][?"template"][?"metadata"][?"annotations"][?"autoscaling.knative.dev/min-scale"].orValue(null))].filter(v, v != null && v != false) + [1])[0]
